import type { Metadata } from 'next'

import Footer from '@/components/Footer/Footer'
import './globals.css'


import { UserProvider } from '@auth0/nextjs-auth0/client'
import AuthProvider from '@/components/AuthProvider/AuthProvider'




export const metadata: Metadata = {
  title: 'Movie Hub Next Application',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" >
      <body className='w-[90%] mx-auto max-w-screen-lg h-[90%]'>
        <UserProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
          <Footer />
        </UserProvider>

      </body>
    </html>
  )
}
