import type { Metadata } from 'next'

import Footer from '@/components/Footer/Footer'
import './globals.css'
import Providers from './providers'
import ThemeBtn from '@/components/ThemeBtn/ThemeBtn'




export const metadata: Metadata = {
  title: 'Movie Hub Next Application',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className='w-[100%] mx-auto max-w-screen-lg h-[90%]'>
        <Providers>
          <ThemeBtn />
          {children}
          <Footer />
        </Providers>


      </body>
    </html>
  )
}
