import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/Footer/Footer'



export const metadata: Metadata = {
  title: 'Movie Hub Next Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-slate-400 bg-hero-shadow-img'>
        <div className='w-[100%] mx-auto max-w-screen-lg h-[90%]'>

          {/* <Navbar /> */}
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
